name: Run My Robot

on:
  workflow_dispatch:

jobs:
  run-bot:
    # تغییر مهم 1: استفاده از لینوکس به جای ویندوز (برای پشتیبانی فارسی)
    runs-on: ubuntu-latest

    steps:
    - name: دانلود کدها
      uses: actions/checkout@v4

    - name: نصب پایتون
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: نصب پیش‌نیازها
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: اتصال به دیتابیس و اجرا
      env:
        GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        # تغییر مهم 2: اجبار پایتون به استفاده از UTF-8 برای چاپ فارسی
        PYTHONIOENCODING: utf-8
      run: |
        python manage.py migrate
        python manage.py scrape_products
