name: Run Scraper on Windows

on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest # <--- تغییر مهم: حتما باید ubuntu باشد تا Xvfb کار کند (ویندوز Xvfb ندارد)

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    # --- بخش جدید: نصب مانیتور مجازی ---
    - name: Install dependencies and Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y xvfb google-chrome-stable  # <--- نصب کروم اصلی
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Scraper with Virtual Display
      env:
        GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        WP_KEY: ${{ secrets.WP_KEY }}
        PYTHONIOENCODING: utf-8
      run: |
        
        # --- دستور جادویی: اجرا داخل محیط مجازی گرافیکی ---
        # این دستور یک مانیتور با رزولوشن 1920x1080 می‌سازد و پایتون را داخل آن اجرا می‌کند
        xvfb-run --auto-servernum --server-args="-screen 0 1920x1080x24" python manage.py discover_products
        
        
